title: BRIGHTBLU Documentation and API
description:
theme: just-the-docs

url: https://Brightblu2020.github.io/docs

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
