title: BRIGHTBLU
description: Firmware/API documentation for BRIGHTBLU Jolt Series Chargers
theme: just-the-docs

url: https://Brightblu2020.github.io/docs

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
